server:
  port: 8585
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_orders_db
    username: postgres
    password: rashadnewpassword
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog-master.yml


